### ISSUE TITLE
Send status to mqtt

### ISSUE THREAD

**Issue by nodiaque** [michaelwoods/onstar2mqtt#234] opened 2022-11-30 13:47 UTC
Hello,

It would be nice to have a status chjannel where the last status is posted. It could be the reply of last command (like unlock/lock), the status of the last refresh and maybe happened the date time and what was last requested. This way at least, we could trap when something doesn't go well easier.

Thank you!

**Comment by glassbase** [comment] 2022-11-30 14:26
Duplicate/ related issue https://github.com/michaelwoods/onstar2mqtt/issues/93

**Comment by michaelwoods** [comment] 2023-02-02 01:54
Duplicate of #93

**Closed by michaelwoods** 2023-02-02 01:54 UTC
