### ISSUE TITLE
Converting to miles, psi etc

### ISSUE THREAD

**Issue by Digitalhour** [michaelwoods/onstar2mqtt#18] opened 2021-03-19 20:58 UTC
I have been trying to convert  kilometers to miles as well as kpa to psi. 
how can this be archived?

**Comment by michaelwoods** [comment] 2021-04-06 16:31
My plan is to add a flag for imperial conversion and add additional topics/sensors with those units. No ETA on that.

**Comment by michaelwoods** [comment] 2021-04-06 16:32
Dupe of #2

**Closed by michaelwoods** 2021-04-06 16:32 UTC
